spring.application.name=quizapp

spring.datasource.url=jdbc:postgresql://localhost:5432/quizapp
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=quizapp
spring.datasource.password=quizapp

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.jwt.secret=1UKCNi0+5t6w/vzo47bP2Ros796QLDaGqGGjj9WTb8cR9uCFx9g/F7/m8ayKhNOK
app.jwt.expiration-ms=86400000
